use_frameworks!

platform :ios, '11.0'

target 'fiuu-mobile-xdk-cocoapods_Example' do
  pod 'fiuu-mobile-xdk-cocoapods', :path => '../'

  target 'fiuu-mobile-xdk-cocoapods_Tests' do
    inherit! :search_paths

    
  end
end
